### ISSUE TITLE
The order of the themes in the pdf is wrong

### ISSUE THREAD

**Issue by ghost** [etalab/barometre-resultats-documentation#2]
If there are more than 9 themes, the pdf generated by the script https://github.com/etalab/barometre-resultats-documentation/blob/master/doc_pdf/main.py puts the 10th category after the 1st. Something having to do with 10 after 1?

**Comment by geoffreyaldebert** [comment]
probably, will check tomorrow

**Comment by ghost** [comment]
Solved with [commit 3fec6b2cb660343f954744b9020c3264349a52c3](https://github.com/etalab/barometre-resultats-documentation/commit/3fec6b2cb660343f954744b9020c3264349a52c3)
